version: "3"

services:
  
  postgres:
    image: postgres:latest
    container_name: splicing-prediction-postgres
    environment:
      POSTGRES_DB: splicing-prediction-db
      POSTGRES_USER: admin 
      POSTGRES_PASSWORD: 5rxJ52P8QTn
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  postgres-data:
  redis-data:
